In [1]:
import numpy as np

import pandas as pd
import unittest

In [2]:
train_features = pd.read_csv('train.csv')
target_features = pd.read_csv('train_features.csv')

In [9]:
features = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])
test_w_i_h = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
test_w_h_o = np.array([[0.3],
                       [-0.1]])


In [50]:
target_features.shape

(1, 1)

In [51]:
#features = np.array(train_features[:2])

In [52]:
#targets = np.array(target_features[:2])

In [53]:
features.shape


(1, 3)

In [54]:
targets.shape

(1, 1)

In [55]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [56]:
features.shape[1]

3

In [57]:
input_nodes = features.shape[1]
hidden_nodes = 2
output_nodes = 1

# Initialize weights
weights_input_to_hidden = np.random.normal(0.0, input_nodes**-0.5, 
                               (input_nodes, hidden_nodes))

weights_hidden_to_output = np.random.normal(0.0, hidden_nodes**-0.5, 
                               (hidden_nodes, output_nodes))
lr = 0.5


In [58]:
weights_input_to_hidden.shape

(3, 2)

In [59]:
weights_hidden_to_output.shape

(2, 1)

In [60]:
#Forward pass

hidden_inputs = np.dot(features,weights_input_to_hidden) # signals into hidden layer
hidden_outputs = sigmoid(hidden_inputs) # signals from hidden layer

# TODO: Output layer - Replace these values with your calculations.
final_inputs = np.dot(hidden_outputs,weights_hidden_to_output) # signals into final output layer
final_outputs = final_inputs # signals from final output layer
final_outputs

array([[ 0.37386077]])

In [61]:
error = targets - final_outputs
error

array([[ 0.02613923]])

In [62]:

# TODO: Backpropagated error terms - Replace these values with your calculations.
output_error_term = error * final_outputs * (1 - final_outputs)
output_error_term

array([[ 0.0061189]])

In [63]:
hidden_error =  np.dot(error, weights_hidden_to_output.T)

In [64]:
hidden_error.shape

(1, 2)

In [65]:
hidden_error_term = hidden_error *hidden_outputs *  (1-hidden_outputs)

In [66]:
hidden_error_term.shape

(1, 2)

In [67]:
n_records = features.shape[0]
delta_weights_i_h = np.zeros(weights_input_to_hidden.shape)
delta_weights_h_o = np.zeros(weights_hidden_to_output.shape)

In [68]:
delta_weights_h_o.shape

(2, 1)

In [69]:
delta_weights_i_h.shape

(3, 2)

In [70]:
features.shape

(1, 3)

In [71]:
hidden_error_term.shape

(1, 2)

In [72]:
np.dot(hidden_error_term.T,features).shape

(2, 3)

In [73]:
delta_weights_i_h +=  np.dot(features.T, hidden_error_term)


In [74]:
delta_weights_i_h.shape

(3, 2)

In [75]:
output_error_term.shape

(1, 1)

In [76]:
hidden_inputs.T.shape

(2, 1)

In [77]:
delta_weights_h_o += np.dot(hidden_inputs.T, output_error_term)

In [78]:
delta_weights_h_o.shape

(2, 1)

In [79]:
weights_hidden_to_output += lr * delta_weights_h_o/n_records

In [80]:
weights_input_to_hidden += lr * delta_weights_i_h/n_records

In [81]:
delta_weights_i_h.shape

(3, 2)

In [95]:
for X, y in zip(features, targets):
    print(X[:,None].T.shape)
    print(y[None,:].shape)

(1, 3)
(1, 1)


In [88]:
features.shape

(1, 3)

In [93]:
y[None,:].shape

(1, 1)

In [ ]:


class TestMethods(unittest.TestCase):
    
    ##########
    # Unit tests for data loading
    ##########
    
    def test_data_path(self):
        # Test that file path to dataset has been unaltered
        self.assertTrue(data_path.lower() == 'bike-sharing-dataset/hour.csv')
        
    def test_data_loaded(self):
        # Test that data frame loaded
        self.assertTrue(isinstance(rides, pd.DataFrame))
    
    ##########
    # Unit tests for network functionality
    ##########

    def test_activation(self):
        network = NeuralNetwork(3, 2, 1, 0.5)
        # Test that the activation function is a sigmoid
        self.assertTrue(np.all(network.activation_function(0.5) == 1/(1+np.exp(-0.5))))

    def test_train(self):
        # Test that weights are updated correctly on training
        network = NeuralNetwork(3, 2, 1, 0.5)
        network.weights_input_to_hidden = test_w_i_h.copy()
        network.weights_hidden_to_output = test_w_h_o.copy()
        
        network.train(inputs, targets)
        self.assertTrue(np.allclose(network.weights_hidden_to_output, 
                                    np.array([[ 0.37275328], 
                                              [-0.03172939]])))
        self.assertTrue(np.allclose(network.weights_input_to_hidden,
                                    np.array([[ 0.10562014, -0.20185996], 
                                              [0.39775194, 0.50074398], 
                                              [-0.29887597, 0.19962801]])))

    def test_run(self):
        # Test correctness of run method
        network = NeuralNetwork(3, 2, 1, 0.5)
        network.weights_input_to_hidden = test_w_i_h.copy()
        network.weights_hidden_to_output = test_w_h_o.copy()

        self.assertTrue(np.allclose(network.run(inputs,targets), 0.09998924))

suite = unittest.TestLoader().loadTestsFromModule(TestMethods())
unittest.TextTestRunner().run(suite)

In [2]:

class NeuralNetwork(object):
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_input_to_hidden = np.random.normal(0.0, self.input_nodes**-0.5, 
                                       (self.input_nodes, self.hidden_nodes))

        self.weights_hidden_to_output = np.random.normal(0.0, self.hidden_nodes**-0.5, 
                                       (self.hidden_nodes, self.output_nodes))
        self.lr = learning_rate
        
        #### TODO: Set self.activation_function to your implemented sigmoid function ####
        #
        # Note: in Python, you can define a function with a lambda expression,
        # as shown below.
        self.activation_function = lambda x : 1/(1 + np.exp(-x))  # Replace 0 with your sigmoid calculation.
        
        ### If the lambda code above is not something you're familiar with,
        # You can uncomment out the following three lines and put your 
        # implementation there instead.
        #
        #def sigmoid(x):
        #    return 0  # Replace 0 with your sigmoid calculation here
        #self.activation_function = sigmoid
                    

    def train(self, features, targets):
        ''' Train the network on batch of features and targets. 
        
            Arguments
            ---------
            
            features: 2D array, each row is one data record, each column is a feature
            targets: 1D array of target values
        
        '''
        n_records = features.shape[0]
        delta_weights_i_h = np.zeros(self.weights_input_to_hidden.shape)
        delta_weights_h_o = np.zeros(self.weights_hidden_to_output.shape)
        for X, y in zip(features, targets):
            
            final_outputs, hidden_outputs = self.forward_pass_train(X)  # Implement the forward pass function below
            # Implement the backproagation function below
            delta_weights_i_h, delta_weights_h_o = self.backpropagation(final_outputs, hidden_outputs, X, y, 
                                                                        delta_weights_i_h, delta_weights_h_o)
        self.update_weights(delta_weights_i_h, delta_weights_h_o, n_records)


    def forward_pass_train(self, X):
        ''' Implement forward pass here 
         
            Arguments
            ---------
            X: features batch

        '''
        #### Implement the forward pass here ####
        ### Forward pass ###
        # TODO: Hidden layer - Replace these values with your calculations.
        hidden_inputs = np.dot(X,self.weights_input_to_hidden) # signals into hidden layer
        hidden_outputs = self.activation_function(hidden_inputs) # signals from hidden layer

        # TODO: Output layer - Replace these values with your calculations.
        final_inputs = np.dot(hidden_outputs,self.weights_hidden_to_output) # signals into final output layer
        final_outputs = final_inputs # signals from final output layer
        
        return final_outputs, hidden_outputs

    def backpropagation(self, final_outputs, hidden_outputs, X, y, delta_weights_i_h, delta_weights_h_o):
        ''' Implement backpropagation
         
            Arguments
            ---------
            final_outputs: output from forward pass
            y: target (i.e. label) batch
            delta_weights_i_h: change in weights from input to hidden layers
            delta_weights_h_o: change in weights from hidden to output layers

        '''
        #### Implement the backward pass here ####
        ### Backward pass ###

        # TODO: Output error - Replace this value with your calculations.
        error = y - final_outputs # Output layer error is the difference between desired target and actual output.
        
        # TODO: Calculate the hidden layer's contribution to the error
        hidden_error = np.dot(error * self.weights_hidden_to_output)
        
        # TODO: Backpropagated error terms - Replace these values with your calculations.
        output_error_term = error * final_output * (1 - final_output)
        
        hidden_error_term = hidden_error * hidden_output * (1 - hidden_output)
        
        # Weight step (input to hidden)
        delta_weights_i_h += np.dot(X.T * output_error_term)
        # Weight step (hidden to output)
        delta_weights_h_o += np.dot(hidden_inputs * output_error_term.T)
        return delta_weights_i_h, delta_weights_h_o

    def update_weights(self, delta_weights_i_h, delta_weights_h_o, n_records):
        ''' Update weights on gradient descent step
         
            Arguments
            ---------
            delta_weights_i_h: change in weights from input to hidden layers
            delta_weights_h_o: change in weights from hidden to output layers
            n_records: number of records

        '''
        self.weights_hidden_to_output += lr * delta_weights_h_o # update hidden-to-output weights with gradient descent step
        self.weights_input_to_hidden += lr * delta_weights_i_h  # update input-to-hidden weights with gradient descent step

    def run(self, features):
        ''' Run a forward pass through the network with input features 
        
            Arguments
            ---------
            features: 1D array of feature values
        '''
        
        #### Implement the forward pass here ####
        # TODO: Hidden layer - replace these values with the appropriate calculations.
        
        
        #hidden_inputs = None # signals into hidden layer
        #hidden_outputs = None # signals from hidden layer
        
        # TODO: Output layer - Replace these values with the appropriate calculations.
        #final_inputs = None # signals into final output layer
        final_outputs = None
        #, hidden_outputs = forward_pass_train(features) # signals from final output layer 
        
        #train()
        
        return final_outputs



In [3]:

#########################################################
# Set your hyperparameters here
##########################################################
iterations = 100
learning_rate = 0.1
hidden_nodes = 2
output_nodes = 1
