In [1]:
import numpy as np

In [2]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [7]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [8]:
t.shape

(3, 3, 2, 1)

In [17]:
a = np.array([[1,2,3],[3,4,3],[6,4,3]])
a

array([[1, 2, 3],
       [3, 4, 3],
       [6, 4, 3]])

In [18]:
np.dot(a,a)

array([[25, 22, 18],
       [33, 34, 30],
       [36, 40, 39]])

In [15]:
np.matmul(a,a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [65]:
a = [-1,2,7]

In [66]:
b = np.array(a)

In [67]:
b - min(b)

array([0, 3, 8])

In [72]:
min(b)*-1

1

In [73]:
max(b)

7

In [60]:
b - 1

array([-2,  1,  6])

In [70]:
np.subtract(b,1)

array([-2,  1,  6])

In [ ]:
np.divide

In [53]:
np.ndarray()

AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [45]:
np.array(b[None,:])

array([[2, 3, 8]])

In [46]:
np.ndarray(b[None,:])

TypeError: only integer scalar arrays can be converted to a scalar index

In [86]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 =  np.array([[1,2]])

In [89]:
m1.shape

(2, 3)

In [87]:
m2.shape

(1, 2)

In [88]:
np.matmul(m1,m2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [81]:
m1.shape[1]

3

In [82]:
m2.shape[0]

4

In [ ]:
np.matmul()

In [90]:
l = [1,3,4]

In [92]:
Input as Array: [[-1  2  7]]
Input minus min: [[-2  4 14]]
Input  Array: [[1. 1. 1.]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
False
Mean == 2.6666666666666665

An ndarray prepare_inputs returned includ

2.6666666666666665

In [93]:
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]

In [96]:
a = np.array(test_inputs)

In [100]:
a

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [99]:
np.matmul(a)

ValueError: invalid number of arguments

In [ ]:
np.log10

In [4]:
x = np.array([1, 2, 3, 4])
w = np.array([0.5, -0.5, 0.3, 0.1])

In [5]:
x*w

array([ 0.5, -1. ,  0.9,  0.4])

In [14]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))



# TODO: Make a forward pass through the network

hidden_layer_in = np.matmul(X,weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.matmul(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]


In [12]:

# TODO: Make a forward pass through the network

hidden_layer_in = np.matmul(X,weights_input_to_hidden)
hidden_layer_out = np.matmul(hidden_layer_in, weights_hidden_to_output)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = hidden_layer_out
output_layer_out = sigmoid(hidden_layer_out)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[-0.00827738 -0.01151895]
Output-layer Output:
[0.49793067 0.49712029]


In [3]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [4]:
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [6]:
X = np.random.randn(4)


In [9]:
np.matmul(np.matmul(X,weights_input_to_hidden), weights_hidden_to_output)

array([-0.00827738, -0.01151895])

In [10]:
hidden_layer_out

NameError: name 'hidden_layer_out' is not defined

In [15]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)


In [17]:

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1-output)



# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term,weights_hidden_output )* hidden_layer_output * (1 -hidden_layer_output)
hidden_error_term


# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_input
delta_w_h_o

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h =(learnrate * hidden_error_term) * x[:,None] 
delta_w_i_h


print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


In [37]:
weights_input_hidden

array([[ 0.5, -0.6],
       [ 0.1, -0.2],
       [ 0.1,  0.7]])